### ISSUE TITLE
lack of source file "utils.py"

### ISSUE THREAD

**Issue by YSS9264** [JieJayCao/Encrypted-Traffic-Classification-Models#1]
build_dataset, build_iterator, get_time_dif

**Comment by JieCaoSec** [comment]
I have updated the "utils" files, and you can build your own dataset input torch interface based on the data input structure of the original papers.

**Comment by Tina23Tian** [comment]
Could you provide the content of the check function in the process_datanet_vpn.py file?

**Comment by JieCaoSec** [comment]
**check** is a function that checks the number of samples in each class for undersampling, and if the number of samples is less than a threshold you can continue to preprocess the PCAP file for that class.
